theme = "smol"
title = "Daren Liang"

[params]
    subtitle = ""
    dateFmt = "02.01.2006"

[menu]
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		url = "/posts/"
		weight = 1

	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 2

	[[menu.main]]
		identifier = "projects"
		name = "Projects"
		url = "/projects/"
		weight = 3

	[[menu.main]]
		identifier = "resume"
		name = "Resume"
		url = "/resume/"
		weight = 4

	[[menu.footer]]
		name = "Github"
        url = "https://github.com/darenliang"
        weight = 1

	[[menu.footer]]
		name = "Email"
        url = "mailto:daren@darenliang.com"
        weight = 2
