baseURL: /
languageCode: en-us
title: darenliang
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: Daren Liang's Website

  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false

  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowToc: false
  tocopen: false

  disableSpecial1stPost: false
  comments: false
  hidemeta: false

  profileMode:
    enabled: true
    title: Daren Liang

  assets:
    favicon: img/favicon.png

  socialIcons:
    - name: Github
      url: "https://github.com/darenliang"
    - name: Email
      url: "mailto:daren@darenliang.com"
    - name: Rss
      url: "index.xml"

menu:
  main:
    - name: Blog
      identifier: posts
      url: posts
      weight: 1
    - name: About
      identifier: about
      url: about
      weight: 2
    - name: Projects
      identifier: projects
      url: projects
      weight: 3
    - name: Resume
      identifier: resume
      url: /doc/resume.pdf
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
