baseURL = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Show reading time in minutes for posts
  showReadingTime = false
  author = "Daren Liang"

  [[params.social]]
    name = "email"
    url  = "mailto:daren@darenliang.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/darenliang"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/darenliang"

[languages]
  [languages.en]
    title = "darenliang"
    subtitle = ""
    description = "Daren Liang's Personal Website"
    keywords = ""
    copyright = "© <script type=\"text/javascript\">document.write(new Date().getFullYear());</script> Daren Liang"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "darenliang"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Daren Liang"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 3

      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Résume"
        url = "/doc/resume.pdf"
        weight = 3
